---

- name: Install Git
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ git_packages }}"

- name: Configure Git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
  - name: user.name
    value: "{{ git_username }}"
  - name: user.email
    value: "{{ git_email }}"
  - "{{ git_config }}"


- name: Set git aliases
  git_config:
    name: "alias.{{ item.alias }}"
    value: "{{ item.value }}"
    scope: global
  with_items: "{{ git_alias }}"

- name: Authorize key with GitHub
  github_key:
    name: '{{ git_github_key_name }}'
    token: '{{ git_github_token }}'
    force: no
    pubkey: "{{ lookup('file', '/home/{{ workstation_bootstrap_username }}/.ssh/id_rsa.pub') }}"
  when: git_github_token is defined

- name: Checkout Git repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    version: "{{ item.version|default(omit) }}"
    update: no
  with_items: "{{ git_repository }}"


